:docinfo: shared

== Gradle Plugin

As noted in Quick Start, add the plugin with

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Groovy
----
plugins {
    id 'org.ethelred.kiwiproc' version '{revnumber}'
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="primary"]
.Kotlin
----
plugins {
    id("org.ethelred.kiwiproc").version("{revnumber}")
}
----

With no additional configuration, this will assume:

* A single datasource named "default".
* A Liquibase changelog in "src/main/resources/changelog.xml".
* Use `jakarta.inject` annotations in generated code.

All available properties with their default values:

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Groovy
----
import org.ethelred.kiwiproc.processorconfig.DependencyInjectionStyle

kiwiProc {
    dependencyInjectionStyle = DependencyInjectionStyle.JAKARTA // <1>
    debug = false // <2>
    addDependencies = true // <3>
    liquibaseChangelog = file("$projectDir/src/main/resources/changelog.xml") // <4>
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="primary"]
.Kotlin
----
import org.ethelred.kiwiproc.processorconfig.DependencyInjectionStyle

kiwiProc {
    dependencyInjectionStyle = DependencyInjectionStyle.JAKARTA // <1>
    debug = false // <2>
    addDependencies = true // <3>
    liquibaseChangelog = file("$projectDir/src/main/resources/changelog.xml") // <4>
}
----
<1> Change to `DependencyInjectionStyle.SPRING` for use with Spring.
<2> Enabling debug will make the annotation processor print more details during compilation.
<3> Disabling "add dependencies" will prevent the plugin adding kiwiproc dependencies to the build. This is primarily for testing.
<4> Change the path for liquibase for the "default" datasource. It is not valid when using multiple datasources - see below.

=== Liquibase

When using an embedded database, a schema must be defined. Liquibase is the supported way to do this.
Therefore, a Liquibase changelog file is _required_, except when using an external database.

=== Embedded H2

To use embedded H2 instead of PostgreSQL, set `driverClassName` to the H2 driver class name.
H2 is a pure-Java in-memory database — no Docker required.

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Groovy
----
kiwiProc {
    dataSources {
        register("default") {
            driverClassName = "org.h2.Driver" // <1>
            liquibaseChangelog = file("$projectDir/src/main/resources/changelog.xml")
        }
    }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="primary"]
.Kotlin
----
kiwiProc {
    dataSources {
        register("default") {
            driverClassName = "org.h2.Driver" // <1>
            liquibaseChangelog = file("$projectDir/src/main/resources/changelog.xml")
        }
    }
}
----
<1> Setting `driverClassName` to the H2 driver selects embedded H2.

See xref:databases.adoc#h2-limitations[H2 Limitations] for a list of features not available with H2.

=== Embedded MySQL

To use embedded MySQL instead of PostgreSQL, set `driverClassName` to the MySQL driver class name.
This requires Docker to be available on the build machine (Testcontainers is used internally).

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Groovy
----
kiwiProc {
    dataSources {
        register("default") {
            driverClassName = "com.mysql.cj.jdbc.Driver" // <1>
            liquibaseChangelog = file("$projectDir/src/main/resources/changelog.xml")
        }
    }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="primary"]
.Kotlin
----
kiwiProc {
    dataSources {
        register("default") {
            driverClassName = "com.mysql.cj.jdbc.Driver" // <1>
            liquibaseChangelog = file("$projectDir/src/main/resources/changelog.xml")
        }
    }
}
----
<1> Setting `driverClassName` to the MySQL driver selects embedded MySQL via Testcontainers/Docker.

See xref:databases.adoc#mysql-limitations[MySQL Limitations] for a list of features not available with MySQL.

=== Multiple and External Datasources

KiwiProc supports using more than one datasource in a project.

[source,java]
----
@DAO(dataSourceName = "firstDatabase") // <1>
interface FirstDatabaseDAO {
    //...
}
----
<1> Specify the datasource name in an interface.

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Groovy
----
kiwiProc {
    dataSources {
        register("firstDatabase") { // <1>
            liquibaseChangelog = file("$projectDir/src/main/resources/first/changelog.xml")
        }
        register("secondDatabase") {
            liquibaseChangelog = file("$projectDir/src/main/resources/somepath/changelog.xml")
        }
        register("externalDatabase") { // <2>
            jdbcUrl = "jdbc:postgresql://db.example.com/database"
            // optional
            database = "..."
            username = "..."
            password = "..." // <3>
        }
        register("externalMySQL") { // <4>
            jdbcUrl = "jdbc:mysql://db.example.com/database"
            username = "..."
            password = "..."
        }
        register("externalH2") { // <5>
            jdbcUrl = "jdbc:h2:file:/path/to/database"
        }
    }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="primary"]
.Kotlin
----
kiwiProc {
    dataSources {
        register("firstDatabase") { // <1>
            liquibaseChangelog = file("$projectDir/src/main/resources/first/changelog.xml")
        }
        register("secondDatabase") {
            liquibaseChangelog = file("$projectDir/src/main/resources/somepath/changelog.xml")
        }
        register("externalDatabase") { // <2>
            jdbcUrl = "jdbc:postgresql://db.example.com/database"
            // optional
            database = "..."
            username = "..."
            password = "..." // <3>
        }
        register("externalMySQL") { // <4>
            jdbcUrl = "jdbc:mysql://db.example.com/database"
            username = "..."
            password = "..."
        }
        register("externalH2") { // <5>
            jdbcUrl = "jdbc:h2:file:/path/to/database"
        }
    }
}
----
<1> Register one or more datasources.
<2> An external PostgreSQL datasource is specified by giving a JDBC URL. Liquibase changelog is _optional_ for an external datasource.
<3> How to manage secret values for Gradle builds, is out of scope for this document.
<4> An external MySQL datasource uses a `jdbc:mysql://` URL.
<5> An external H2 datasource uses a `jdbc:h2:` URL.

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Groovy
----
kiwiProc {
    dataSources {
        register("default") { // <1>
            jdbcUrl = "jdbc:postgresql://db.example.com/database"
        }
    }
}
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="primary"]
.Kotlin
----
kiwiProc {
    dataSources {
        register("default") { // <1>
            jdbcUrl = "jdbc:postgresql://db.example.com/database"
        }
    }
}
----
<1> To use an external database for the "default" datasource, configure it in the dataSources block.

[[test-properties]]
=== Test properties

A file named `application-test.properties` will be written to the test resources path, so that automated tests can use the same database.

The property key depends on the `dependencyInjectionStyle`:

For `JAKARTA` (the default) and Micronaut:

[source,properties]
----
datasources.default.url=jdbc\:postgresql\://localhost\:42581/rgtnmpgbihhy?user\=postgres
----

For `SPRING`:

[source,properties]
----
spring.datasource.url=jdbc\:postgresql\://localhost\:42581/rgtnmpgbihhy?user\=postgres
----

This is the standard Spring Boot property for datasource auto-configuration.
Combined with the `kiwiproc-spring-autoconfigure` module (added automatically by the plugin), no manual `DataSource` bean definition is needed in tests.

For MySQL, credentials are embedded in the URL as query parameters:

[source,properties]
----
datasources.default.url=jdbc\:mysql\://localhost\:3306/test?user\=root&password\=secret
----

Other code can read the properties file with `java.util.Properties`.