plugins {
    `java-library`
    jacoco
    checkstyle
    id("com.diffplug.spotless")
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy(tasks.named("jacocoTestReport"))
}

tasks.named<JacocoReport>("jacocoTestReport") {
    dependsOn(tasks.named("test"))
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

// buildSrc's own precompiled script plugins can't use the generated `libs.xxx` accessors
// (chicken-and-egg: those accessors are generated by compiling this same buildSrc build),
// so look the catalog up explicitly instead.
val libs = the<VersionCatalogsExtension>().named("libs")

dependencies {
    implementation("org.jspecify:jspecify:1.0.1")
    testImplementation(libs.findLibrary("junit-jupiter").get())
    testImplementation(libs.findLibrary("junit-params").get())
    testImplementation(libs.findLibrary("truth").get())
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

checkstyle {
    configFile = rootProject.file("config/checkstyle/checkstyle.xml")
}

configurations.named("checkstyle") {
    resolutionStrategy.force(
        "commons-beanutils:commons-beanutils:1.11.0",
        "org.codehaus.plexus:plexus-utils:4.1.0"
    )
}

dependencies {
    constraints {
        implementation("org.apache.commons:commons-lang3") {
            version { require("3.18.0") }
            because("Dependabot CVE: uncontrolled recursion below 3.18.0")
        }
        implementation("org.apache.commons:commons-compress") {
            version { require("1.26.0") }
            because("Dependabot CVE: DoS/OOM below 1.26.0")
        }
    }
}

spotless {
    java {
        cleanthat()
        importOrder()
        removeUnusedImports()
        palantirJavaFormat()
        formatAnnotations()
        licenseHeader("/* (C) Edward Harman \$YEAR */")
    }
}